business_name: Brewinghood
tagline: Your neighborhood coffeeshop
phone: (555) 555-1111
address: 123 Main Street, Anytown NY
hours: Mon-Fri 11am-10pm, Sat-Sun 10am-11pm
menu_items:
  - name: White Coffee
    description: Bright citrus and pine, 6.5% ABV
    price: '7.00'
  - name: Brown Coffee
    description: Bavarian wheat, banana and clove, 5.2% ABV
    price: '6.50'
  - name: Coconut Coffee
    description: Dark roasted malt, chocolate finish, 7.1% ABV
    price: '7.50'
  - name: Creamy Salt Coffee
    description: Dark roasted malt, chocolate finish, 7.1% ABV
    price: '7.50'
