business_name: Brewinghood Coffeebar Da Nang
social_accounts:
  - name: Google Maps
    icon: fa-solid fa-location-dot
    url: https://maps.app.goo.gl/PtkXcd536jWHdWb67
  - name: Threads
    icon: fa-brands fa-threads
    url: https://www.threads.com/@brewinghood.coffeebar
  - name: Instagram
    icon: fa-brands fa-instagram
    url: https://www.instagram.com/brewinghood.coffeebar
  - name: Facebook
    icon: fa-brands fa-facebook
    url: https://www.facebook.com/profile.php?id=61551374516268
hours: 09:00 - 18:00
hours_note: closed thursdays
background_image: /assets/uploads/hero.webp
beans_heading: seasonal beans
beans_copy: We rotate beans regularly. There is always something new to try!
menu_title: our menu
menu_copy: Full Coffee Bar, plus a few extras!
address: 123 Main Street, Anytown NY
tagline: Your neighborhood coffeeshop
phone: (555) 555-1111
menu_items:
  - name: White Coffee 2
    description: Bright citrus and pine, 6.5% ABV
    price: '7.00'
  - name: Brown Coffee
    description: Bavarian wheat, banana and clove, 5.2% ABV
    price: '6.50'
  - name: Coconut Coffee
    description: Dark roasted malt, chocolate finish, 7.1% ABV
    price: '7.50'
  - name: Creamy Salt Coffee
    description: Dark roasted malt, chocolate finish, 7.1% ABV
    price: '7.50'
